name: GitHub Pages

on:
  push:
    branches:
      - master

# Courtesy of _Github actions with R_, available: https://ropenscilabs.github.io/actions_sandbox/

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      # - uses: r-lib/actions/setup-r@v1
      # - uses: r-lib/actions/setup-pandoc@v1
      # - name: Install R Markdown and Bookdown packages
      #   run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      # - name: Install TinyTeX
      #   run: Rscript -e 'tinytex::install_tinytex()'
      # - name: Build Book
      #   run: |
      #     set -ev
      #     cd book
      #     Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
      #     Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
      #     Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/_book
          publish_branch: gh-pages