on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: bookdown

env:
  isExtPR: ${{ github.event.pull_request.head.repo.fork == true }}

jobs:
  build:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install more system dependencies
        run: |
          brew install --cask xquartz
          brew install pkg-config cairo
          brew install gsl
          brew install libxml2

      - name: Build site
        run: |
          Rscript -e 'install.packages(c("tidyverse", "nycflights13", "hexbin", "gapminder", "Lahman"))'
          Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/_book
          publish_branch: gh-pages